### PR TITLE
Changes to use the chef package resource to install wkhtmltopdf

### PR DESCRIPTION
**Pull request by shiftyeyes**
* Changes to use the chef package resource to install wkhtmltopdf
* Adds chef_wkhtmltopdf_cleanup recipe to remove wkhtmltopdf installed by previous chef-wkhtmltopdf cookbook

### CODE REVIEW

**Comment by shiftyeyes** [comment]
After this is pulled in, could a release be performed. We currently use Red Hat OS and would love to use this cookbook. Thanks!

**Comment by BallisticPain** [comment]
@shiftyeyes I will have to do the release later tonight. I haven't worked with chef / berkshelf / knife in over a month so it'll take me a few minutes.

**Comment by shiftyeyes** [comment]
@BallisticPain I'm not sure if you noticed, but your v.0.3.2 tag, the metadata.rb still has version 0.3.1. Thanks for cutting the release for me!

https://github.com/BallisticPain/chef-wkhtmltopdf/blob/v0.3.2/metadata.rb#L7

**Comment by BallisticPain** [comment]
@shiftyeyes I did notice... (After I released of course). Also if you're interested in getting it from the supermarket I have it up there after a while of figuring all this out again.

**Comment by BallisticPain** [comment]
Of course I thought I had a version mismatch, but it was trying to upload an empty version as 0.1.0 which already existed so I jumped to 0.4.0, but oh well.

**Pull request merged**
